name: Update badges

on:
  workflow_dispatch:    
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-badges:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install requests
        run: pip install requests
      - name: Update README badges
        run: python update_badges.py
      - name: Commit & push changes
        env:
          TOKEN: ${{ secrets.PUSH_TOKEN }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add README.md
          git commit -m "🔄 Auto-update badges"
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }} HEAD:main

